language: android
jdk: oraclejdk8

env:
  global:
  - ADB_INSTALL_TIMEOUT=10
  matrix:
  - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a  TEST_SUITE=static
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a  TEST_SUITE=integration

android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - extra-android-m2repository
  - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease
